### ISSUE TITLE
Rename the default branch of this repo from `master` to `main`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-viewer#155]
See https://github.com/ampproject/amphtml/issues/32195 for more details

**Comment by rsimha** [comment]
@ericfs From reading the code in this repo, looks like there's nothing that's relying on the default branch name. I'm happy to do the renaming if you'd like.

**Comment by ericfs** [comment]
That would be great. Thank you!

**Comment by rsimha** [comment]
Done!

![image](https://user-images.githubusercontent.com/26553114/115764449-90bffd80-a373-11eb-85fc-076b8e4fbd8d.png)
